substitutions:
  device_name: "esphome-smart-curtain-00"
  friendly_name: "Smart Curtain (00)"
  project_name: "tuya.smart-curtain-motor"
  project_version: "1.0"

esphome:
  name: "${device_name}"
  friendly_name: ${friendly_name}
  #name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

  on_boot:
    priority: -100
    then:
      - lambda: |-
          auto temp = ESP.getResetReason();
          id( reset_reason).publish_state( temp.c_str());

esp8266:
  board: esp8285
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

# Enable logging
# Levels:
#   - ERROR: ESP_LOGE
#   - WARNING: ESP_LOGW
#   - INFO: ESP_LOGI
#   - DEBUG: ESP_LOGD
#   - VERBOSE: ESP_LOGV
#   - VERY_VERBOSE: ESP_LOGVV
logger:
  level: NONE
  #esp8266_store_log_strings_in_flash: false
  baud_rate: 0
  
api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 18
  #power_save_mode: LIGHT
  use_address: 192.168.3.14
  ap: #{} # This spawns an AP with the device name and mac address with no password.
    ssid: "${device_name}"
    password: !secret wifi_ap_password

captive_portal:

# web_server:
#   port: 80
#   local: true
#   auth:
#     username: !secret web_server_username
#     password: !secret web_server_password

# Time Source
# time:
#   - platform: homeassistant
#     id: homeassistant_time
  # - platform: sntp
  #   id: sntp_time

# Status LED
light:
  - platform: status_led
    id: led1
    pin:
      number: GPIO02
      inverted: true

uart:
  id: uart_tuya
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  data_bits: 8 # 5...8
  parity: NONE # EVEN, ODD
  stop_bits: 1 # 1...2

tuya:
  # time_id: homeassistant_time


# Soft Buttons
button:
  - platform: factory_reset
    id: reset_btn
    name: "Reset to Factory Defaults"
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: restart
    id: restart_btn
    name: "Restart"
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: safe_mode
    id: safemode_btn
    name: "Safe Mode"
    entity_category: "diagnostic"
    disabled_by_default: true


####################
#      SENSORS     #
####################
sensor:
# Diagnostic
  - platform: uptime
    name: "Uptime"
    icon: mdi:clock-start
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal (dB)"
    icon: mdi:signal
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    disabled_by_default: true
  
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal (%)"
    icon: mdi:signal
    filters:
    - lambda: return min( max( 2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    disabled_by_default: true


####################
#  BINARY SENSORS  #
####################
binary_sensor:
# Diagnostic
  - platform: status
    name: "Status"
    id: connection_status
    entity_category: "diagnostic"
    #disabled_by_default: true


####################
#   TEXT SENSORS   #
####################
text_sensor:
# Diagnostic
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip-network-outline
      entity_category: "diagnostic"

    mac_address:
      name: MAC Address
      entity_category: "diagnostic"

  - platform: template
    id: reset_reason
    name: Reset Reason
    icon: mdi:progress-question
    entity_category: "diagnostic"


####################
#      COVER       #
####################
cover:
  - platform: tuya
    name: "Control"
    control_datapoint: 1
    position_datapoint: 2
    min_value: 0
    max_value: 100
    position_report_datapoint: 3
    direction_datapoint: 5

####################
#      SELECT      #
####################
select:
  - platform: tuya
    enum_datapoint: 5
    id: tuya_direction
    name: "Direction"
    icon: mdi:rotate-3d-variant
    entity_category: config
    optimistic: true
    options:
     0: "Forward"
     1: "Reverse"